name: Build Delphi Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Delphi environment and  Build with MSBuild
        shell: cmd
        run: |
          SET BDS=C:\Program Files (x86)\Embarcadero\Studio\23.0
          SET BDSINCLUDE=C:\Program Files (x86)\Embarcadero\Studio\23.0\include
          SET BDSCOMMONDIR=C:\Users\Public\Documents\Embarcadero\Studio\23.0
          SET FrameworkDir=C:\Windows\Microsoft.NET\Framework\v4.0.30319
          SET FrameworkVersion=v4.5
          SET FrameworkSDKDir=
          SET PATH=%FrameworkDir%;%FrameworkSDKDir%;C:\Program Files (x86)\Embarcadero\Studio\23.0\bin;C:\Program Files (x86)\Embarcadero\Studio\23.0\bin64;C:\Program Files (x86)\Embarcadero\Studio\23.0\cmake;%PATH%
          SET LANGDIR=EN
          SET PLATFORM=
          SET PlatformSDK=
          msbuild XebiaDelphiDemo1.dproj /t:Build /p:Config=Debug /p:Platform=Win64
          dir
          cd Win64/Debug
          dir

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DelphiBuildArtifacts
          path: ./Win64/Debug
