name: Build Delphi Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Delphi environment
        run: |
          "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          echo %BDS%
      - name: Build with MSBuild
        run: |
          msbuild XebiaDelphiDemo1.dproj /t:Build /p:Config=Debug /p:Platform=Win64
