name: Build Delphi Project

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Lazarus
        uses: sxmxta/lazarus@v1.0.18
        with:
          lazarus-version: stable

      - name: Build with lazbuild
        run: lazbuild XebiaDelphiDemo1.lpi --bm=Default

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DelphiBuildArtifacts
          path: ./lib/x86_64-win64
