name: Build Delphi Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Delphi environment and  Build with MSBuild
        shell: cmd
        run: |
          "C:\Program Files (x86)\Embarcadero\Studio\23.0\bin\rsvars.bat"
          msbuild XebiaDelphiDemo1.dproj /t:Build /p:Config=Debug /p:Platform=Win64
          dir
          cd Win64/Debug
          dir

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DelphiBuildArtifacts
          path: ./Win64/Debug
