name: Build Delphi Project

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with Lazarus lazbuild
        run: |
          C:/lazarus/lazbuild.exe XebiaDelphiDemo1.lpi --bm=Default

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DelphiBuildArtifacts
          path: ./lib/x86_64-win64
