name: Build Delphi Project

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build with MSBuild
        run: |
          & msbuild XebiaDelphiDemo1.dproj /t:Build /p:Config=Debug /p:Platform=Win32
